"""
Greenhouse board-token registry.

Greenhouse's public Job Board API is scoped by board token, not by global
job search. This registry gives the scraper a broad candidate universe and
the scraper skips tokens that return 404.
"""

from __future__ import annotations


EUROPE_TECH_BOARDS = [
    # AI / ML and AI-native companies
    "openai",
    "anthropic",
    "deepmind",
    "mistralai",
    "wayve",
    "elevenlabs",
    "synthesia",
    "stabilityai",
    "huggingface",
    "cohere",
    "scaleai",
    "snorkelai",
    "databricks",
    "wandb",
    "weightsandbiases",
    "pinecone",
    "modal",
    "replicate",
    "perplexity",
    "adept",
    "inflection",
    "characterai",
    "runwayml",
    "assemblyai",
    "deepgram",
    "descript",
    "sana",
    "poolside",
    "dust",
    "helsing",
    "alephalpha",
    "instadeep",
    "isomorphiclabs",
    "benevolentai",
    "exscientia",
    "faculty",
    "polyai",
    "speechmatics",
    "veed",
    "papercup",
    "quantinuum",
    "graphcore",
    "darktrace",
    "blackforestlabs",
    "thinkingmachines",
    # European fintech, insurtech, and payments
    "monzo",
    "wise",
    "revolut",
    "starlingbank",
    "gocardless",
    "checkout",
    "checkoutcom",
    "adyen",
    "mollie",
    "klarna",
    "n26",
    "pleo",
    "qonto",
    "alan",
    "payfit",
    "swile",
    "personio",
    "celonis",
    "mambu",
    "traderepublic",
    "trade-republic",
    "scalablecapital",
    "bunq",
    "tink",
    "truelayer",
    "zopa",
    "oaknorth",
    "iwoca",
    "fundingcircle",
    "atombank",
    "atom-bank",
    "tandem",
    "curve",
    "sumup",
    "primer",
    "form3",
    "thoughtmachine",
    "griffin",
    "griffinbank",
    "tide",
    "rapyd",
    "payhawk",
    "wefox",
    "ledger",
    "fireblocks",
    "rampnetwork",
    "moonpay",
    "worldcoin",
    "toolsforhumanity",
    "complyadvantage",
    "onfido",
    "yoti",
    "paddle",
    "wayflyer",
    # Logistics, mobility, travel, and marketplaces
    "zencargo",
    "sennder",
    "forto",
    "flink",
    "gorillas",
    "getir",
    "bolt",
    "wolt",
    "deliveroo",
    "justeat",
    "takeaway",
    "hellofresh",
    "getyourguide",
    "travelperk",
    "omio",
    "trainline",
    "skyscanner",
    "kiwi",
    "booking",
    "backmarket",
    "vestiairecollective",
    "vinted",
    "depop",
    "wallapop",
    "olx",
    "leboncoin",
    "idealista",
    "rightmove",
    "zoopla",
    "housinganywhere",
    "carwow",
    "motorway",
    "cazoo",
    # Developer tools, infrastructure, and SaaS
    "spotify",
    "soundcloud",
    "deezer",
    "nativeinstruments",
    "zalando",
    "aboutyou",
    "typeform",
    "miro",
    "figma",
    "canva",
    "notion",
    "airtable",
    "asana",
    "slack",
    "discord",
    "loom",
    "linear",
    "deel",
    "remote",
    "retool",
    "vercel",
    "netlify",
    "supabase",
    "postman",
    "hashicorp",
    "elastic",
    "snyk",
    "gitlab",
    "grafana",
    "confluent",
    "mongodb",
    "redis",
    "clickhouse",
    "cockroachlabs",
    "neon",
    "planetscale",
    "temporal",
    "tailscale",
    "cloudflare",
    "twilio",
    "segment",
    "stripe",
    "dropbox",
    "box",
    "zapier",
    "hubspot",
    "intercom",
    "zendesk",
    "aircall",
    "front",
    "contentsquare",
    "datadog",
    "amplitude",
    "mixpanel",
    "braze",
    "algolia",
    "auth0",
    "okta",
    "docker",
    "canonical",
    "mongodb",
    "elasticco",
    "mattermost",
    # UK and European deep tech, energy, health, and education
    "arm",
    "improbable",
    "improbableio",
    "oxfordnanopore",
    "octopusenergy",
    "octopus",
    "krakentech",
    "kraken-tech",
    "ovoenergy",
    "bulb",
    "multiverse",
    "beamery",
    "doctolib",
    "babylonhealth",
    "adahealth",
    "kry",
    "livi",
    "healx",
    "hazy",
    "humanloop",
    "prolific",
    "primerai",
    "quantumblack",
    "secondmind",
    "fiveai",
    "oxbotica",
    "waymo",
    "arrival",
    "northvolt",
    "climeworks",
    "watershed",
    "plan-a",
    "carbonchain",
    "wunderflats",
    "sennder",
    "lilium",
    "volocopter",
    "skydio",
    # Gaming, media, and consumer tech with European presence
    "unity",
    "epicgames",
    "rovio",
    "supercell",
    "king",
    "miniclip",
    "faceit",
    "ccpgames",
    "fandom",
    "reddit",
    "pinterest",
    "snap",
    "tiktok",
    "bytedance",
    "meta",
    "netflix",
    "spotifyjobs",
    # Additional high-signal tech companies using or known to have used boards
    "coinbase",
    "kraken",
    "chainalysis",
    "consensys",
    "brex",
    "affirm",
    "chime",
    "robinhood",
    "ramp",
    "airbnb",
    "uber",
    "doordash",
    "instacart",
    "asana",
    "calendly",
    "rippling",
    "gusto",
    "verkada",
    "rubrik",
    "snowflake",
    "servicenow",
    "workato",
    "zapier",
    "qualtrics",
    "atlassian",
    "monday",
    "mondaycom",
    "wix",
    "similarweb",
    "riskified",
    "outbrain",
    "taboola",
    "payoneer",
    "fiverr",
    "getir",
    "yotpo",
    "gong",
    "deel",
    "snyk",
    "semgrep",
    "sourcegraph",
    "circleci",
    "launchdarkly",
    "pagerduty",
    "dataminr",
    "duolingo",
]


PRESETS = {
    "europe_tech": EUROPE_TECH_BOARDS,
}


def resolve_greenhouse_boards(
    configured_boards: list[str] | None = None,
    presets: list[str] | None = None,
) -> list[str]:
    selected_presets = presets if presets is not None else ["europe_tech"]
    boards: list[str] = []
    for preset in selected_presets:
        boards.extend(PRESETS.get(preset, []))
    boards.extend(configured_boards or [])
    return _unique(_normalize_token(token) for token in boards)


def _normalize_token(token: str) -> str:
    return str(token or "").strip().strip("/").split("/")[-1].lower()


def _unique(tokens) -> list[str]:
    seen = set()
    unique = []
    for token in tokens:
        if not token or token in seen:
            continue
        seen.add(token)
        unique.append(token)
    return unique
